# Generated by Django 6.0.6 on 2026-07-03 00:29

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('course', 'دوره'), ('institution_faq', 'سوالات متداول موسسه')], max_length=20, verbose_name='نوع منبع')),
                ('content', models.TextField(verbose_name='محتوای متنی (شامل متادیتای پایدار)')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='هش محتوا (برای تشخیص تغییرات پایدار)')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True, verbose_name='بردار (Embedding)')),
                ('embedding_model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل Embedding')),
                ('embedded_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان Embedding')),
                ('metadata', models.JSONField(default=dict, verbose_name='متادیتای پویا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('source_course_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='courses.coursedetail', verbose_name='جزئیات دوره منبع')),
            ],
            options={
                'verbose_name': 'تکه دانش (Chunk)',
                'verbose_name_plural': 'تکه\u200cهای دانش (Chunks)',
            },
        ),
    ]
