# Generated by Django 6.0.6 on 2026-07-02 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='نام دوره')),
                ('instructor', models.CharField(blank=True, max_length=255, verbose_name='مدرس')),
                ('schedule', models.CharField(blank=True, max_length=500, verbose_name='زمان برگزاری')),
                ('start_date', models.CharField(blank=True, max_length=100, verbose_name='تاریخ شروع (متن خام)')),
                ('start_date_parsed', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع (پارس شده)')),
                ('start_note', models.CharField(blank=True, max_length=255, verbose_name='توضیحات شروع')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='مدت دوره (ساعت)')),
                ('capacity_remaining', models.PositiveIntegerField(default=0, verbose_name='ظرفیت باقی\u200cمانده')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت اصلی')),
                ('final_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت نهایی')),
                ('discount_description', models.CharField(blank=True, max_length=500, verbose_name='توضیحات تخفیف')),
                ('status', models.CharField(choices=[('enrolling', 'در حال ثبت\u200cنام'), ('filling', 'در حال تکمیل ظرفیت'), ('full', 'تکمیل ظرفیت')], default='enrolling', max_length=20, verbose_name='وضعیت ثبت\u200cنام')),
                ('sub_courses', models.JSONField(blank=True, default=list, verbose_name='زیردوره\u200cها')),
                ('url', models.URLField(unique=True, verbose_name='لینک دوره')),
                ('start_status', models.CharField(choices=[('confirmed', 'قطعی'), ('pending_capacity', 'منوط به تکمیل ظرفیت'), ('undecided', 'نامشخص')], default='undecided', max_length=20, verbose_name='وضعیت شروع')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('url', models.URLField(unique=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'جزئیات دوره',
                'verbose_name_plural': 'جزئیات دوره\u200cها',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.department', verbose_name='دپارتمان'),
        ),
    ]
