# Generated by Django 6.0.6 on 2026-07-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='coursedetail',
            table='course_details',
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
    ]
