# Generated by Django 6.0.6 on 2026-07-03 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='شماره تماس')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('needs_followup', 'نیازمند پیگیری'), ('converted', 'تبدیل شده')], default='new', max_length=20, verbose_name='وضعیت')),
                ('aggregated_summary', models.TextField(blank=True, verbose_name='خلاصه تجمیعی مکالمات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'ردیابی (Lead)',
                'verbose_name_plural': 'ردیابی\u200cها (Leads)',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='leads.lead', verbose_name='ردیابی')),
            ],
            options={
                'verbose_name': 'مکالمه',
                'verbose_name_plural': 'مکالمه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'کاربر'), ('bot', 'بات')], max_length=10, verbose_name='فرستنده')),
                ('content', models.TextField(verbose_name='متن پیام')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leads.conversation', verbose_name='مکالمه')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['timestamp'],
            },
        ),
    ]
