# Generated by Django 6.0.6 on 2026-07-05 23:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='توکن'),
        ),
    ]
