# Generated by Django 6.0.6 on 2026-07-05 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.UUIDField(db_index=True, editable=False, verbose_name='Trace ID')),
                ('stage', models.CharField(choices=[('query_understanding', 'Query Understanding'), ('routing', 'Routing'), ('retrieval', 'Retrieval'), ('response_generation', 'Response Generation'), ('handoff', 'Human Handoff')], max_length=30, verbose_name='مرحله')),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed_hard', 'Failed (Exception)'), ('success_but_low_confidence', 'Success (Low Confidence)')], max_length=40, verbose_name='نتیجه')),
                ('intent', models.CharField(blank=True, choices=[('course_specific', 'Course Specific'), ('institution_faq', 'Institution FAQ'), ('structured_lookup', 'Structured Lookup'), ('small_talk', 'Small Talk'), ('unclear_needs_clarification', 'Unclear (Needs Clarification)'), ('unclear_unanswerable', 'Unclear (Unanswerable)'), ('out_of_scope', 'Out of Scope')], max_length=40, verbose_name='قصد کاربر (Intent)')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='مدل استفاده شده')),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='تاخیر (میلی\u200cثانیه)')),
                ('input_data', models.JSONField(default=dict, verbose_name='ورودی مرحله')),
                ('output_data', models.JSONField(default=dict, verbose_name='خروجی مرحله')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('retrieved_chunk_ids', models.JSONField(blank=True, default=list, verbose_name='شناسه چانک\u200cهای بازیابی شده')),
                ('similarity_scores', models.JSONField(blank=True, default=list, verbose_name='امتیازات شباهت')),
                ('decision_reason', models.TextField(blank=True, verbose_name='دلیل تصمیم (Routing)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_logs', to='leads.message', verbose_name='پیام کاربر')),
            ],
            options={
                'verbose_name': 'لاگ پایپ\u200cلاین',
                'verbose_name_plural': 'لاگ\u200cهای پایپ\u200cلاین',
                'ordering': ['created_at'],
            },
        ),
    ]
