# Generated by Django 6.0.6 on 2026-07-06 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شخصیت')),
                ('identity_description', models.TextField(verbose_name='توضیحات هویت و برند')),
                ('tone_of_voice', models.CharField(max_length=255, verbose_name='لحن گفتار')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شخصیت بات',
                'verbose_name_plural': 'شخصیت\u200cهای بات',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('welcome_message', 'پیام خوش\u200cآمدگویی'), ('query_understanding', 'درک درخواست کاربر'), ('response_generation', 'تولید پاسخ نهایی'), ('handoff', 'تحویل به انسان')], max_length=30, verbose_name='مرحله')),
                ('system_prompt', models.TextField(help_text='متغیرهای مجاز: {identity_description}, {tone_of_voice}', verbose_name='پرامپت سیستم')),
                ('human_prompt', models.TextField(help_text='برای welcome_message متغیرها: {first_name}, {context}', verbose_name='پرامپت کاربر (شامل متغیرها)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='chatbot.botpersona', verbose_name='شخصیت بات')),
            ],
            options={
                'verbose_name': 'قالب پرامپت',
                'verbose_name_plural': 'قالب\u200cهای پرامپت',
                'unique_together': {('persona', 'stage')},
            },
        ),
    ]
