# Generated by Django 6.0.6 on 2026-07-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_botpersona_prompttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شیفت')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
            ],
            options={
                'verbose_name': 'شیفت کاری',
                'verbose_name_plural': 'شیفت\u200cهای کاری',
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'دوشنبه'), (1, 'سه\u200cشنبه'), (2, 'چهارشنبه'), (3, 'پنجشنبه'), (4, 'جمعه'), (5, 'شنبه'), (6, 'یکشنبه')], verbose_name='روز هفته')),
                ('shifts', models.ManyToManyField(to='chatbot.shift', verbose_name='شیفت\u200cها')),
            ],
            options={
                'verbose_name': 'روز کاری',
                'verbose_name_plural': 'روزهای کاری',
                'unique_together': {('day',)},
            },
        ),
    ]
