# Generated by Django 6.0.6 on 2026-07-10 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_shift_workingday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام موسسه')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'موسسه',
                'verbose_name_plural': 'موسسه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mobile', 'موبایل'), ('landline', 'تلفن ثابت'), ('email', 'ایمیل'), ('whatsapp', 'واتساپ'), ('telegram', 'تلگرام'), ('bale', 'بله')], max_length=20, verbose_name='نوع تماس')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
                ('is_support_number', models.BooleanField(default=False, help_text='اگر فعال باشد، پیامک\u200cهای ارجاع به انسان به این شماره ارسال می\u200cشود.', verbose_name='شماره پشتیبانی (برای ارسال پیامک سیستم)')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='chatbot.institution', verbose_name='موسسه')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس\u200cها',
            },
        ),
    ]
